"""
Placeholder Austin events for prototype testing.
Replace with live API/scraper data in production.

Tag taxonomy lives here — edit TAG_CATEGORIES to add/remove tags.
See also: research/tag-taxonomy.md for the full annotated version.
"""

# ── Full Tag Taxonomy ──────────────────────────────────────────────────────────
# Each key is the internal tag ID (snake_case).
# TAG_DISPLAY maps keys to human-readable labels.
# TAG_CATEGORIES groups them for the onboarding UI.

TAG_DISPLAY = {
    # Nature & Outdoors
    "hiking":               "Hiking",
    "trail_running":        "Trail Running",
    "running":              "Running",
    "cycling":              "Cycling",
    "mountain_biking":      "Mountain Biking",
    "rock_climbing":        "Rock Climbing",
    "bouldering":           "Bouldering",
    "swimming":             "Swimming",
    "kayaking":             "Kayaking",
    "canoeing":             "Canoeing",
    "paddleboarding":       "Paddleboarding",
    "fishing":              "Fishing",
    "camping":              "Camping",
    "stargazing":           "Stargazing",
    "bird_watching":        "Bird Watching",
    "nature_walks":         "Nature Walks",
    "parks":                "Parks",
    "gardens":              "Botanical Gardens",
    "waterfalls":           "Waterfalls",
    "lakes":                "Lakes & Reservoirs",
    "rivers":               "Rivers & Creeks",

    # Fitness & Wellness
    "yoga":                 "Yoga",
    "meditation":           "Meditation",
    "pilates":              "Pilates",
    "crossfit":             "CrossFit",
    "weightlifting":        "Weightlifting",
    "martial_arts":         "Martial Arts",
    "dance_fitness":        "Dance Fitness",
    "group_fitness":        "Group Fitness Classes",
    "stretching":           "Stretching & Mobility",
    "sauna":                "Sauna & Spa",
    "cold_plunge":          "Cold Plunge",
    "breathwork":           "Breathwork",

    # Sports & Recreation
    "disc_golf":            "Disc Golf",
    "volleyball":           "Volleyball",
    "ultimate_frisbee":     "Ultimate Frisbee",
    "soccer":               "Soccer",
    "basketball":           "Basketball",
    "tennis":               "Tennis",
    "pickleball":           "Pickleball",
    "softball":             "Softball",
    "flag_football":        "Flag Football",
    "dodgeball":            "Dodgeball",
    "bowling":              "Bowling",
    "archery":              "Archery",
    "axe_throwing":         "Axe Throwing",
    "mini_golf":            "Mini Golf",
    "go_karts":             "Go-Karts",
    "skating":              "Roller / Ice Skating",
    "swimming_laps":        "Lap Swimming",

    # Food & Drink
    "coffee":               "Coffee",
    "brunch":               "Brunch",
    "food_trucks":          "Food Trucks",
    "restaurants":          "Restaurants",
    "fine_dining":          "Fine Dining",
    "casual_dining":        "Casual Dining",
    "tacos":                "Tacos",
    "bbq":                  "BBQ",
    "pizza":                "Pizza",
    "sushi":                "Sushi",
    "ramen":                "Ramen",
    "thai":                 "Thai",
    "vietnamese":           "Vietnamese",
    "mexican":              "Mexican",
    "italian":              "Italian",
    "indian":               "Indian",
    "mediterranean":        "Mediterranean",
    "american":             "American",
    "vegetarian":           "Vegetarian / Vegan",
    "seafood":              "Seafood",
    "bakeries":             "Bakeries & Pastries",
    "ice_cream":            "Ice Cream & Dessert",
    "craft_beer":           "Craft Beer",
    "wine":                 "Wine",
    "cocktails":            "Cocktails",
    "natural_wine":         "Natural Wine",
    "whiskey":              "Whiskey & Spirits",
    "non_alcoholic":        "Non-Alcoholic Options",
    "markets":              "Farmers Markets",
    "food_halls":           "Food Halls",
    "cooking":              "Cooking & Baking",
    "cooking_class":        "Cooking Classes",

    # Arts & Culture
    "live_music":           "Live Music",
    "classical_music":      "Classical Music",
    "jazz":                 "Jazz",
    "country":              "Country Music",
    "hip_hop":              "Hip-Hop",
    "electronic":           "Electronic / DJ",
    "indie_rock":           "Indie Rock",
    "folk":                 "Folk",
    "comedy":               "Comedy",
    "improv":               "Improv",
    "theater":              "Theater",
    "musicals":             "Musicals",
    "opera":                "Opera",
    "dance_performance":    "Dance Performance",
    "spoken_word":          "Spoken Word / Poetry",
    "film":                 "Film & Cinema",
    "film_festivals":       "Film Festivals",
    "art_galleries":        "Art Galleries",
    "museums":              "Museums",
    "history":              "History & Heritage",
    "street_art":           "Street Art & Murals",
    "public_art":           "Public Art Installations",
    "bookstores":           "Bookstores",
    "book_clubs":           "Book Clubs",
    "literary_events":      "Literary Events / Readings",
    "lectures":             "Lectures & Talks",
    "podcasts_live":        "Live Podcast Recordings",

    # Creative & Making
    "painting":             "Painting",
    "drawing":              "Drawing",
    "printmaking":          "Printmaking",
    "ceramics":             "Ceramics / Pottery",
    "sculpture":            "Sculpture",
    "photography":          "Photography",
    "film_making":          "Filmmaking",
    "music_making":         "Playing Music",
    "songwriting":          "Songwriting",
    "crafts":               "Crafts & DIY",
    "woodworking":          "Woodworking",
    "leatherworking":       "Leatherworking",
    "knitting":             "Knitting & Fiber Arts",
    "jewelry_making":       "Jewelry Making",
    "candle_making":        "Candle / Soap Making",
    "screenprinting":       "Screen Printing",
    "creative_writing":     "Creative Writing",
    "journaling":           "Journaling",
    "graphic_design":       "Graphic Design",
    "fashion":              "Fashion & Style",
    "vintage":              "Vintage & Thrift",

    # Social & Community
    "group_activities":     "Group Activities",
    "community":            "Community Events",
    "meetups":              "Meetups & Clubs",
    "volunteering":         "Volunteering",
    "networking":           "Networking",
    "trivia":               "Trivia Nights",
    "pub_crawls":           "Bar Crawls",
    "game_nights":          "Game Nights",
    "supper_clubs":         "Supper Clubs",
    "hosted_dinners":       "Hosted Dinners",
    "pop_ups":              "Pop-Up Events",
    "festivals":            "Festivals",
    "block_parties":        "Block Parties",
    "neighborhood":         "Neighborhood Events",
    "religious":            "Religious / Spiritual",
    "family_friendly":      "Family Friendly",
    "solo_friendly":        "Great Solo",
    "couples":              "Great for Couples",
    "large_groups":         "Large Groups",
    "small_groups":         "Intimate / Small Groups",
    "pet_friendly":         "Pet Friendly",
    "dogs":                 "Dog-Friendly",

    # Learning & Growth
    "workshops":            "Workshops",
    "classes":              "Classes",
    "language_learning":    "Language Learning",
    "coding":               "Coding / Tech",
    "science":              "Science & Tech",
    "history_talks":        "History Talks",
    "philosophy":           "Philosophy",
    "economics":            "Economics & Finance",
    "politics":             "Civic & Political Events",
    "mindfulness":          "Mindfulness",
    "self_improvement":     "Personal Development",
    "career_dev":           "Career Development",
    "startups":             "Startup & Entrepreneurship",

    # Gaming & Entertainment
    "board_games":          "Board Games",
    "card_games":           "Card Games",
    "tabletop_rpg":         "Tabletop RPG",
    "video_games":          "Video Games",
    "arcade":               "Arcade",
    "escape_rooms":         "Escape Rooms",
    "karaoke":              "Karaoke",
    "trivia_games":         "Quiz / Trivia",
    "movies":               "Movies",
    "concerts":             "Concerts",
    "sports_watching":      "Watching Sports",

    # Relaxation & Slow Living
    "cozy":                 "Cozy & Low-Key",
    "reading":              "Reading",
    "journaling_r":         "Journaling",
    "afternoon_nap":        "Rest & Recharge",
    "slow_mornings":        "Slow Mornings",
    "picnics":              "Picnics",
    "sunset_watching":      "Sunset Watching",
    "bath_spa":             "Bath / Home Spa",

    # Nightlife
    "bars":                 "Bars",
    "rooftop_bars":         "Rooftop Bars",
    "dive_bars":            "Dive Bars",
    "live_music_venues":    "Live Music Venues",
    "dance_clubs":          "Dance Clubs",
    "late_night":           "Late Night",
    "happy_hour":           "Happy Hour",

    # Animals & Nature (specific)
    "animals":              "Animals",
    "dog_parks":            "Dog Parks",
    "wildlife":             "Wildlife",
    "zoos":                 "Zoos & Aquariums",
    "farm_visits":          "Farm Visits",

    # Austin-Specific
    "barton_springs":       "Barton Springs",
    "lake_travis":          "Lake Travis",
    "6th_street":           "6th Street",
    "east_austin":          "East Austin",
    "south_congress":       "South Congress",
    "north_loop":           "North Loop",
    "domain":               "The Domain",
    "mueller":              "Mueller",
    "rainey_street":        "Rainey Street",
    "zilker_park":          "Zilker Park",
    "greenbelt":            "Greenbelt",
    "red_river":            "Red River Cultural District",

    # Travel & Day Trips
    "day_trips":            "Day Trips",
    "road_trips":           "Road Trips",
    "texas_hill_country":   "Texas Hill Country",
    "wineries":             "Wineries & Vineyards",
    "state_parks":          "State Parks",
    "national_parks":       "National Parks",

    # Self-Care & Grooming
    "massage":              "Massage",
    "float_tank":           "Float Tank",
    "acupuncture":          "Acupuncture",
    "manicure":             "Manicure / Nails",
    "skincare_facial":      "Facial & Skincare",
    "hair_salon":           "Hair Salon",

    # Content & Media
    "podcasts":             "Podcasts",
    "audiobooks":           "Audiobooks",
    "documentaries":        "Documentaries",
    "tv_shows":             "TV Shows & Series",
    "video_essays":         "Video Essays",

    # Shopping & Browsing
    "antiques":             "Antiques",
    "flea_markets":         "Flea Markets",
    "record_stores":        "Record Stores",
    "plant_shopping":       "Plant Shopping",
    "bookstore_browsing":   "Bookstore Browsing",
    "thrift_shopping":      "Thrift Shopping",

    # Home & Garden
    "gardening":            "Gardening",
    "home_projects":        "Home Projects & DIY",
    "interior_design":      "Interior Design",
    "houseplants":          "Houseplants",
}

AVAILABLE_TAGS = list(TAG_DISPLAY.keys())

TAG_CATEGORIES = {
    "Nature & Outdoors": [
        "hiking", "trail_running", "running", "cycling", "mountain_biking",
        "rock_climbing", "bouldering", "swimming", "kayaking", "canoeing",
        "paddleboarding", "fishing", "camping", "stargazing", "bird_watching",
        "nature_walks", "parks", "gardens", "waterfalls", "lakes", "rivers",
    ],
    "Fitness & Wellness": [
        "yoga", "meditation", "pilates", "crossfit", "weightlifting",
        "martial_arts", "dance_fitness", "group_fitness", "stretching",
        "sauna", "cold_plunge", "breathwork",
    ],
    "Sports & Recreation": [
        "disc_golf", "volleyball", "ultimate_frisbee", "soccer", "basketball",
        "tennis", "pickleball", "softball", "flag_football", "dodgeball",
        "bowling", "archery", "axe_throwing", "mini_golf", "go_karts",
        "skating", "swimming_laps",
    ],
    "Food & Drink": [
        "coffee", "brunch", "food_trucks", "restaurants", "fine_dining",
        "casual_dining", "tacos", "bbq", "pizza", "sushi", "ramen", "thai",
        "vietnamese", "mexican", "italian", "indian", "mediterranean",
        "american", "vegetarian", "seafood", "bakeries", "ice_cream",
        "craft_beer", "wine", "cocktails", "natural_wine", "whiskey",
        "non_alcoholic", "markets", "food_halls", "cooking", "cooking_class",
    ],
    "Arts & Culture": [
        "live_music", "classical_music", "jazz", "country", "hip_hop",
        "electronic", "indie_rock", "folk", "comedy", "improv", "theater",
        "musicals", "opera", "dance_performance", "spoken_word", "film",
        "film_festivals", "art_galleries", "museums", "history", "street_art",
        "public_art", "bookstores", "book_clubs", "literary_events", "lectures",
        "podcasts_live",
    ],
    "Creative & Making": [
        "painting", "drawing", "printmaking", "ceramics", "sculpture",
        "photography", "film_making", "music_making", "songwriting", "crafts",
        "woodworking", "leatherworking", "knitting", "jewelry_making",
        "candle_making", "screenprinting", "creative_writing", "journaling",
        "graphic_design", "fashion", "vintage",
    ],
    "Social & Community": [
        "group_activities", "community", "meetups", "volunteering", "networking",
        "trivia", "pub_crawls", "game_nights", "supper_clubs", "hosted_dinners",
        "pop_ups", "festivals", "block_parties", "neighborhood", "religious",
        "family_friendly", "solo_friendly", "couples", "large_groups",
        "small_groups", "pet_friendly", "dogs",
    ],
    "Learning & Growth": [
        "workshops", "classes", "language_learning", "coding", "science",
        "history_talks", "philosophy", "economics", "politics", "mindfulness",
        "self_improvement", "career_dev", "startups",
    ],
    "Gaming & Entertainment": [
        "board_games", "card_games", "tabletop_rpg", "video_games", "arcade",
        "escape_rooms", "karaoke", "trivia_games", "movies", "concerts",
        "sports_watching",
    ],
    "Relaxation & Slow Living": [
        "cozy", "reading", "picnics", "sunset_watching", "slow_mornings",
        "bath_spa", "afternoon_nap",
    ],
    "Nightlife": [
        "bars", "rooftop_bars", "dive_bars", "live_music_venues", "dance_clubs",
        "late_night", "happy_hour",
    ],
    "Animals": [
        "animals", "dogs", "dog_parks", "wildlife", "zoos", "farm_visits",
    ],
    "Austin Neighborhoods & Spots": [
        "barton_springs", "lake_travis", "6th_street", "east_austin",
        "south_congress", "north_loop", "domain", "mueller", "rainey_street",
        "zilker_park", "greenbelt", "red_river",
    ],
    "Day Trips & Outdoors": [
        "day_trips", "road_trips", "texas_hill_country", "wineries",
        "state_parks", "national_parks",
    ],
    "Self-Care & Grooming": [
        "massage", "float_tank", "acupuncture", "manicure", "skincare_facial",
        "hair_salon",
    ],
    "Content & Media": [
        "podcasts", "audiobooks", "documentaries", "tv_shows", "video_essays",
    ],
    "Shopping & Browsing": [
        "antiques", "flea_markets", "record_stores", "plant_shopping",
        "bookstore_browsing", "thrift_shopping",
    ],
    "Home & Garden": [
        "gardening", "home_projects", "interior_design", "houseplants",
    ],
}

# ── Category colors for calendar display ──────────────────────────────────────
CAT_COLORS = {
    "Nature & Outdoors":            "#22c55e",
    "Fitness & Wellness":           "#3b82f6",
    "Sports & Recreation":          "#ef4444",
    "Food & Drink":                 "#f97316",
    "Arts & Culture":               "#a855f7",
    "Creative & Making":            "#ec4899",
    "Social & Community":           "#06b6d4",
    "Learning & Growth":            "#84cc16",
    "Gaming & Entertainment":       "#8b5cf6",
    "Relaxation & Slow Living":     "#14b8a6",
    "Nightlife":                    "#f43f5e",
    "Animals":                      "#10b981",
    "Austin Neighborhoods & Spots": "#6366f1",
    "Day Trips & Outdoors":         "#0ea5e9",
    "Self-Care & Grooming":         "#fb7185",
    "Content & Media":              "#64748b",
    "Shopping & Browsing":          "#d946ef",
    "Home & Garden":                "#65a30d",
}

# ── Austin-area notable events & holidays ─────────────────────────────────────
# { date_str: (label, kind) }  kind: holiday | festival | sports | premiere
AUSTIN_SPECIAL_EVENTS = {
    "2025-01-01": ("New Year's Day",  "holiday"),
    "2025-01-20": ("MLK Day",         "holiday"),
    "2025-03-07": ("SXSW Begins",     "festival"),
    "2025-04-18": ("Good Friday",     "holiday"),
    "2025-05-26": ("Memorial Day",    "holiday"),
    "2025-07-04": ("4th of July",     "holiday"),
    "2025-09-01": ("Labor Day",       "holiday"),
    "2025-10-03": ("ACL Fest",        "festival"),
    "2025-11-27": ("Thanksgiving",    "holiday"),
    "2025-12-25": ("Christmas",       "holiday"),
    "2025-12-31": ("New Year's Eve",  "festival"),
    "2026-01-01": ("New Year's Day",  "holiday"),
    "2026-01-19": ("MLK Day",         "holiday"),
    "2026-02-16": ("Presidents Day",  "holiday"),
    "2026-03-13": ("SXSW Begins",     "festival"),
    "2026-04-03": ("Good Friday",     "holiday"),
    "2026-05-25": ("Memorial Day",    "holiday"),
    "2026-07-04": ("4th of July",     "holiday"),
    "2026-09-07": ("Labor Day",       "holiday"),
    "2026-10-02": ("ACL Fest",        "festival"),
    "2026-11-26": ("Thanksgiving",    "holiday"),
    "2026-12-25": ("Christmas",       "holiday"),
    "2026-12-31": ("New Year's Eve",  "festival"),
    "2027-01-01": ("New Year's Day",  "holiday"),
    "2027-03-12": ("SXSW Begins",     "festival"),
    "2027-07-04": ("4th of July",     "holiday"),
    "2027-10-01": ("ACL Fest",        "festival"),
    "2027-11-25": ("Thanksgiving",    "holiday"),
    "2027-12-25": ("Christmas",       "holiday"),
    "2027-12-31": ("New Year's Eve",  "festival"),
}

# Default optimal intervals by tag (days between ideal repeats)
TAG_DEFAULT_INTERVALS = {
    "coffee": 2, "brunch": 5, "running": 3, "trail_running": 4,
    "yoga": 3, "meditation": 2, "cycling": 4, "mountain_biking": 7,
    "hiking": 7, "rock_climbing": 5, "bouldering": 5,
    "swimming": 4, "kayaking": 10, "paddleboarding": 10,
    "markets": 7, "museums": 14, "art_galleries": 10,
    "live_music": 7, "concerts": 10, "comedy": 14,
    "restaurants": 4, "food_trucks": 5, "fine_dining": 14,
    "board_games": 7, "tabletop_rpg": 7,
    "bookstores": 10, "book_clubs": 14,
    "ceramics": 14, "painting": 10, "photography": 7,
    "crafts": 10, "woodworking": 14,
    "disc_golf": 7, "tennis": 5, "pickleball": 5,
    "volleyball": 7, "soccer": 7, "basketball": 5,
    "dance_fitness": 5, "group_fitness": 4,
    "theater": 21, "film": 7, "film_festivals": 30,
    "picnics": 10, "stargazing": 14,
    "volunteering": 14, "meetups": 10,
    "workshops": 14, "classes": 7,
    "escape_rooms": 21, "axe_throwing": 21,
    "karaoke": 14, "trivia": 10,
    "bars": 7, "rooftop_bars": 10,
    "day_trips": 21, "road_trips": 30,
    "wineries": 21, "state_parks": 14,
    "sauna": 7, "cold_plunge": 5,
    "bird_watching": 10, "fishing": 14,
    "dog_parks": 5, "farm_visits": 21,
}
DEFAULT_INTERVAL = 7


# Maps event title → Austin neighborhood cluster (for "link nearby" feature)
EVENT_NEIGHBORHOODS = {
    # Morning
    "Morning Yoga at Barton Creek Greenbelt": "greenbelt",
    "SFC Farmers Market — Republic Square":   "downtown",
    "Sunrise Run — Lady Bird Lake Trail":      "zilker",
    "Slow Pour Coffee & Biscuits":             "east_austin",
    "Barton Springs Pool — Early Swim":        "zilker",
    "East Austin Morning Bike Loop":           "east_austin",
    "Guided Bird Walk — Hornsby Bend":         "east_austin",
    "Trail Run — Barton Creek Greenbelt":      "greenbelt",
    "Zilker Park Sunrise Meditation":          "zilker",
    # Midday
    "Blanton Museum of Art":                   "downtown",
    "South Congress Food Truck Row":           "south_lamar",
    "Austin Nature & Science Center":          "zilker",
    "Intro Pottery at Clay House":             "south_lamar",
    "Eastside Community Book Market":          "east_austin",
    "Rock Climbing — Red Cliffs Gym":          "south_lamar",
    "Hyde Park Neighborhood Walk":             "north_austin",
    "Austin History Center":                   "downtown",
    "Escape Room — Cloak & Dagger":            "north_austin",
    "Pickleball Open Play — Kramer Courts":    "north_austin",
    # Afternoon
    "Kayaking on Town Lake":                   "zilker",
    "Disc Golf at Circle C Ranch Meadows":     "south_lamar",
    "Board Games at The Cardboard Café":       "east_austin",
    "Photography Walk — East 6th Murals":      "east_austin",
    "Norwood Estate Dog Park":                 "zilker",
    "Swing Dance Lesson at Speakeasy Ballroom":"downtown",
    "Vintage Shopping — South Lamar Strip":    "south_lamar",
    "Axe Throwing — Stumpy's":                 "downtown",
    "UT Botanic Garden & Wildflower Center":   "south_lamar",
    "Pickup Basketball — Metz Recreation Center":"east_austin",
    # Dinner
    "Odd Duck — Creative Texas Cuisine":       "south_lamar",
    "Kemuri Tatsu-ya — Japanese Izakaya":      "east_austin",
    "La Condesa — Modern Mexican":             "downtown",
    "Salty Sow — Gastropub & Craft Beer":      "east_austin",
    "Pho Saigon Noodle Bar":                   "east_austin",
    "Lenoir — Backyard Farm-to-Table":         "south_lamar",
    "Salt & Time Butcher Shop Dinner":         "east_austin",
    "Contigo — Texas Hill Country Cooking":    "east_austin",
    "Uchi — Modern Japanese":                  "south_lamar",
    "Nixta Taqueria":                          "east_austin",
    # Nighttime
    "Live Music at The Continental Club":      "south_lamar",
    "Comedy Night at Cap City Comedy Club":    "north_austin",
    "Rooftop Drinks at Geraldine's":           "rainey",
    "Late Night Jam — The Parish on 6th":      "downtown",
    "Improv Show — Coldtowne Theater":         "north_austin",
    "Jazz at Elephant Room":                   "downtown",
    "Karaoke at Ego's":                        "south_lamar",
    "Rainey Street Bar Hop":                   "rainey",
    "Stay In — Low-Key Evening":               "home",
}

NEIGHBORHOOD_LABELS = {
    "greenbelt":   "Greenbelt",
    "downtown":    "Downtown",
    "zilker":      "Zilker / Lady Bird",
    "east_austin": "East Austin",
    "south_lamar": "South Lamar",
    "north_austin":"North Austin",
    "rainey":      "Rainey Street",
    "home":        "Home",
}

SEED_EVENTS = [
    # ── MORNING ───────────────────────────────────────────────────────────────
    {
        "title": "Morning Yoga at Barton Creek Greenbelt",
        "block": "morning",
        "tags": ["yoga", "nature_walks", "parks", "solo_friendly", "barton_springs", "greenbelt"],
        "location": "Barton Creek Greenbelt Trailhead",
        "address": "3755 S Capital of Texas Hwy",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 60,
        "description": "Community yoga session in the shade of the greenbelt. Mats provided — just bring water and sunscreen. Wraps up before the heat sets in.",
        "distance_miles": 4.2,
    },
    {
        "title": "SFC Farmers Market — Republic Square",
        "block": "morning",
        "tags": ["markets", "community", "food_trucks", "solo_friendly", "brunch", "neighborhood"],
        "location": "Republic Square Park",
        "address": "422 W 4th St",
        "cost_label": "Free entry",
        "cost_dollars": 0,
        "duration_min": 90,
        "description": "Local produce, artisan goods, breakfast tacos, and cold brew from rotating vendors. One of Austin's best Saturday morning traditions.",
        "distance_miles": 2.8,
    },
    {
        "title": "Sunrise Run — Lady Bird Lake Trail",
        "block": "morning",
        "tags": ["running", "nature_walks", "lakes", "parks", "solo_friendly", "zilker_park"],
        "location": "Lady Bird Lake Hike & Bike Trail",
        "address": "S Congress Ave & Riverside Dr",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 50,
        "description": "Austin's most popular trail loop — 10 miles around the lake with city skyline views. Go before 9am to beat the heat and the crowd.",
        "distance_miles": 1.5,
    },
    {
        "title": "Slow Pour Coffee & Biscuits",
        "block": "morning",
        "tags": ["coffee", "cozy", "solo_friendly", "east_austin", "slow_mornings", "bakeries"],
        "location": "Slow Pour Coffee House",
        "address": "2206 E Cesar Chavez St",
        "cost_label": "$8–14",
        "cost_dollars": 11,
        "duration_min": 75,
        "description": "East Austin neighborhood spot with exceptional pour-overs, fresh biscuits, and a quiet reading room in the back. Good for a slow morning.",
        "distance_miles": 3.1,
    },
    {
        "title": "Barton Springs Pool — Early Swim",
        "block": "morning",
        "tags": ["swimming", "nature_walks", "barton_springs", "lakes", "solo_friendly", "cold_plunge"],
        "location": "Barton Springs Pool",
        "address": "2201 Barton Springs Rd",
        "cost_label": "$5",
        "cost_dollars": 5,
        "duration_min": 90,
        "description": "Fed by underground springs, a constant 68°F year-round. The morning swim here is one of Austin's most beloved rituals.",
        "distance_miles": 3.8,
    },
    {
        "title": "East Austin Morning Bike Loop",
        "block": "morning",
        "tags": ["cycling", "east_austin", "solo_friendly", "community", "street_art"],
        "location": "Boggy Creek Greenbelt (start)",
        "address": "1814 Nance St",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 60,
        "description": "Flat 8-mile loop through East Austin neighborhoods. Murals, coffee stops, and minimal traffic. Bring your own bike or rent from nearby B-Cycle.",
        "distance_miles": 2.0,
    },
    {
        "title": "Guided Bird Walk — Hornsby Bend",
        "block": "morning",
        "tags": ["bird_watching", "nature_walks", "wildlife", "solo_friendly", "rivers"],
        "location": "Hornsby Bend Bird Observatory",
        "address": "2210 FM 973, Austin",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 120,
        "description": "One of Texas's premier bird-watching spots. Seasonal migrations bring hundreds of species. Volunteer naturalists lead free morning walks on weekends.",
        "distance_miles": 9.4,
    },
    {
        "title": "Trail Run — Barton Creek Greenbelt",
        "block": "morning",
        "tags": ["trail_running", "hiking", "greenbelt", "barton_springs", "nature_walks"],
        "location": "Barton Creek Greenbelt — Spyglass Entry",
        "address": "2642 Barton Hills Dr",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 75,
        "description": "8+ miles of shaded trail with creek crossings and limestone ledges. Go at first light before it gets crowded. Bring water — no fountains past the first mile.",
        "distance_miles": 3.5,
    },
    {
        "title": "Zilker Park Sunrise Meditation",
        "block": "morning",
        "tags": ["meditation", "parks", "zilker_park", "solo_friendly", "breathwork", "slow_mornings"],
        "location": "Zilker Park Great Lawn",
        "address": "2100 Barton Springs Rd",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 45,
        "description": "Drop-in group meditation led by a local teacher every Sunday at sunrise. Bring a mat or blanket. All levels welcome — first-timers especially.",
        "distance_miles": 3.2,
    },
    # ── MIDDAY ────────────────────────────────────────────────────────────────
    {
        "title": "Blanton Museum of Art",
        "block": "midday",
        "tags": ["museums", "art_galleries", "solo_friendly", "painting", "history"],
        "location": "Blanton Museum of Art",
        "address": "200 E Martin Luther King Jr Blvd",
        "cost_label": "$12",
        "cost_dollars": 12,
        "duration_min": 90,
        "description": "UT's flagship art museum with rotating exhibitions and a permanent collection spanning centuries. Great air conditioning on hot days.",
        "distance_miles": 2.2,
    },
    {
        "title": "South Congress Food Truck Row",
        "block": "midday",
        "tags": ["food_trucks", "south_congress", "community", "tacos", "casual_dining"],
        "location": "S Congress Ave Food Trucks",
        "address": "S Congress Ave & E Gibson St",
        "cost_label": "$10–18",
        "cost_dollars": 14,
        "duration_min": 60,
        "description": "A string of Austin's best food trucks: breakfast tacos all day, Thai, Indian, and fusion within walking distance of each other.",
        "distance_miles": 3.5,
    },
    {
        "title": "Austin Nature & Science Center",
        "block": "midday",
        "tags": ["nature_walks", "animals", "museums", "parks", "wildlife", "family_friendly"],
        "location": "Austin Nature & Science Center",
        "address": "2389 Stratford Dr",
        "cost_label": "Free (donations welcome)",
        "cost_dollars": 0,
        "duration_min": 90,
        "description": "Free nature center with live native wildlife, interactive exhibits, and shaded trails. Underrated weekday escape.",
        "distance_miles": 5.1,
    },
    {
        "title": "Intro Pottery at Clay House",
        "block": "midday",
        "tags": ["ceramics", "crafts", "small_groups", "community", "workshops"],
        "location": "Clay House Austin",
        "address": "5407 Manchaca Rd",
        "cost_label": "$35",
        "cost_dollars": 35,
        "duration_min": 120,
        "description": "Drop-in wheel-throwing session for beginners. All materials included. Walk out with a bowl to be fired — pick it up next week.",
        "distance_miles": 4.7,
    },
    {
        "title": "Eastside Community Book Market",
        "block": "midday",
        "tags": ["bookstores", "community", "solo_friendly", "east_austin", "markets", "literary_events"],
        "location": "Plaza Saltillo",
        "address": "412 Comal St",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 60,
        "description": "Used books, zines, and local authors. Run by volunteers every weekend with rotating literary events and readings.",
        "distance_miles": 1.9,
    },
    {
        "title": "Rock Climbing — Red Cliffs Gym",
        "block": "midday",
        "tags": ["rock_climbing", "bouldering", "sports", "solo_friendly", "group_activities"],
        "location": "Red Cliffs Climbing Gym",
        "address": "4401 Freidrich Ln",
        "cost_label": "$20 day pass",
        "cost_dollars": 20,
        "duration_min": 90,
        "description": "Austin's largest indoor climbing gym with bouldering and top-rope walls. Gear rental available. Lively social scene on weekend afternoons.",
        "distance_miles": 6.3,
    },
    {
        "title": "Hyde Park Neighborhood Walk",
        "block": "midday",
        "tags": ["nature_walks", "photography", "solo_friendly", "history", "neighborhood"],
        "location": "Hyde Park",
        "address": "E 38th St & Guadalupe St",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 60,
        "description": "Austin's most architecturally charming neighborhood. Craftsman bungalows, shaded sidewalks, and the best lemonade stand in the city.",
        "distance_miles": 3.0,
    },
    {
        "title": "Austin History Center",
        "block": "midday",
        "tags": ["history", "museums", "solo_friendly", "lectures", "history_talks"],
        "location": "Austin History Center",
        "address": "810 Guadalupe St",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 75,
        "description": "Austin's main archive and local history museum in a beautiful 1933 building. Rotating exhibits on Austin's past — often surprising.",
        "distance_miles": 2.0,
    },
    {
        "title": "Escape Room — Cloak & Dagger",
        "block": "midday",
        "tags": ["escape_rooms", "small_groups", "group_activities", "game_nights"],
        "location": "Cloak & Dagger Escape Rooms",
        "address": "3423 Guadalupe St",
        "cost_label": "$28/person",
        "cost_dollars": 28,
        "duration_min": 75,
        "description": "Four themed rooms, 2–8 players. Book ahead on weekends. The 'Victorian Manor' room is the fan favorite. Great for a group outing.",
        "distance_miles": 3.8,
    },
    {
        "title": "Pickleball Open Play — Kramer Courts",
        "block": "midday",
        "tags": ["pickleball", "sports", "community", "group_activities", "social_friendly"],
        "location": "Kramer Lane Pickleball Courts",
        "address": "6900 Kramer Ln",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 90,
        "description": "Austin's most popular open-play pickleball location. Friendly rec players of all levels. Just show up — the regulars are welcoming.",
        "distance_miles": 7.2,
    },
    # ── AFTERNOON ─────────────────────────────────────────────────────────────
    {
        "title": "Kayaking on Town Lake",
        "block": "afternoon",
        "tags": ["kayaking", "nature_walks", "lakes", "solo_friendly", "paddleboarding"],
        "location": "Rowing Dock — Town Lake",
        "address": "2418 Stratford Dr",
        "cost_label": "$25/hr",
        "cost_dollars": 25,
        "duration_min": 90,
        "description": "Paddle around Lady Bird Lake with skyline views. Kayak and SUP rentals available. Stay until sunset to catch the bat bridge emergence.",
        "distance_miles": 4.0,
    },
    {
        "title": "Disc Golf at Circle C Ranch Meadows",
        "block": "afternoon",
        "tags": ["disc_golf", "parks", "solo_friendly", "sports", "nature_walks"],
        "location": "Circle C Ranch Meadows Park",
        "address": "6301 W William Cannon Dr",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 90,
        "description": "Shaded 18-hole disc golf course in a park setting. Free to play, bring your own discs or borrow from regulars at the first tee.",
        "distance_miles": 8.1,
    },
    {
        "title": "Board Games at The Cardboard Café",
        "block": "afternoon",
        "tags": ["board_games", "small_groups", "game_nights", "cozy", "trivia_games"],
        "location": "The Cardboard Café",
        "address": "2211 E 6th St",
        "cost_label": "$7 cover + drinks",
        "cost_dollars": 12,
        "duration_min": 120,
        "description": "Pay a cover, pick from 800+ games, order drinks. Game coaches available. Great for a group or surprisingly fun solo.",
        "distance_miles": 2.5,
    },
    {
        "title": "Photography Walk — East 6th Murals",
        "block": "afternoon",
        "tags": ["photography", "street_art", "east_austin", "art_galleries", "solo_friendly"],
        "location": "East 6th Street Arts District",
        "address": "E 6th St & Waller St",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 75,
        "description": "Austin's most photogenic street murals in a 4-block stretch. Golden hour (4–6pm) makes this especially worth it — plan accordingly.",
        "distance_miles": 2.1,
    },
    {
        "title": "Norwood Estate Dog Park",
        "block": "afternoon",
        "tags": ["dog_parks", "animals", "community", "parks", "nature_walks", "dogs", "pet_friendly"],
        "location": "Norwood Estate Dog Park",
        "address": "1123 Norwood Park Blvd",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 60,
        "description": "One of Austin's busiest off-leash parks on the lake. Good social scene even without a dog — regulars are very welcoming.",
        "distance_miles": 3.3,
    },
    {
        "title": "Swing Dance Lesson at Speakeasy Ballroom",
        "block": "afternoon",
        "tags": ["dance_fitness", "dance_performance", "community", "live_music", "group_activities", "small_groups"],
        "location": "Speakeasy Ballroom",
        "address": "412 Congress Ave",
        "cost_label": "$15",
        "cost_dollars": 15,
        "duration_min": 90,
        "description": "Beginner swing lesson every Saturday afternoon. No partner required — instructor handles rotations. Social dance session follows the lesson.",
        "distance_miles": 1.8,
    },
    {
        "title": "Vintage Shopping — South Lamar Strip",
        "block": "afternoon",
        "tags": ["vintage", "south_congress", "fashion", "solo_friendly", "community"],
        "location": "S Lamar Vintage Row",
        "address": "S Lamar Blvd & Oltorf St",
        "cost_label": "Free to browse",
        "cost_dollars": 0,
        "duration_min": 75,
        "description": "Three vintage/thrift stores in a two-block stretch, plus a record store and an outdoor plant market. Low-pressure browsing.",
        "distance_miles": 3.6,
    },
    {
        "title": "Axe Throwing — Stumpy's",
        "block": "afternoon",
        "tags": ["axe_throwing", "group_activities", "large_groups", "small_groups"],
        "location": "Stumpy's Hatchet House",
        "address": "412 Congress Ave #200",
        "cost_label": "$25/person",
        "cost_dollars": 25,
        "duration_min": 75,
        "description": "Instructed axe-throwing lanes for 2–24 people. No experience needed. Walk-ins on weekdays; book ahead on weekends.",
        "distance_miles": 1.9,
    },
    {
        "title": "UT Botanic Garden & Wildflower Center",
        "block": "afternoon",
        "tags": ["gardens", "nature_walks", "photography", "solo_friendly", "bird_watching", "parks"],
        "location": "Lady Bird Johnson Wildflower Center",
        "address": "4801 La Crosse Ave",
        "cost_label": "$12",
        "cost_dollars": 12,
        "duration_min": 90,
        "description": "350 acres of Texas native plants, wildflower meadows, and stone architecture. Peak blooms in March–May but worth visiting year-round.",
        "distance_miles": 7.8,
    },
    {
        "title": "Pickup Basketball — Metz Recreation Center",
        "block": "afternoon",
        "tags": ["basketball", "sports", "community", "group_activities", "east_austin"],
        "location": "Metz Recreation Center",
        "address": "2407 Canterbury St",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 90,
        "description": "Open gym pickup basketball most weekday and weekend afternoons. Friendly competitive level. Regulars of all ages.",
        "distance_miles": 2.6,
    },
    # ── DINNER ────────────────────────────────────────────────────────────────
    {
        "title": "Odd Duck — Creative Texas Cuisine",
        "block": "dinner",
        "tags": ["fine_dining", "american", "south_congress", "wine", "couples"],
        "location": "Odd Duck",
        "address": "1201 S Lamar Blvd",
        "cost_label": "$30–50/person",
        "cost_dollars": 40,
        "duration_min": 90,
        "description": "Farm-to-table small plates with a Texas twist. Seasonal menu changes weekly. One of Austin's most consistent top-tier restaurants.",
        "distance_miles": 3.2,
        "cuisine": "American / New Texas",
    },
    {
        "title": "Kemuri Tatsu-ya — Japanese Izakaya",
        "block": "dinner",
        "tags": ["restaurants", "sushi", "east_austin", "cocktails", "couples", "small_groups"],
        "location": "Kemuri Tatsu-ya",
        "address": "2713 E 2nd St",
        "cost_label": "$25–45/person",
        "cost_dollars": 35,
        "duration_min": 90,
        "description": "Smoke, sake, and yakitori skewers in a converted service station. Go early or expect a 45-minute wait — worth it both ways.",
        "distance_miles": 2.3,
        "cuisine": "Japanese",
    },
    {
        "title": "La Condesa — Modern Mexican",
        "block": "dinner",
        "tags": ["mexican", "community", "cocktails", "couples", "small_groups"],
        "location": "La Condesa",
        "address": "400 W 2nd St",
        "cost_label": "$20–40/person",
        "cost_dollars": 30,
        "duration_min": 90,
        "description": "Upscale modern Mexican with excellent mezcal cocktails and a lively patio. Downtown location makes it easy to extend into a night out.",
        "distance_miles": 2.0,
        "cuisine": "Mexican",
    },
    {
        "title": "Salty Sow — Gastropub & Craft Beer",
        "block": "dinner",
        "tags": ["american", "craft_beer", "casual_dining", "community", "small_groups"],
        "location": "Salty Sow",
        "address": "1917 Manor Rd",
        "cost_label": "$15–30/person",
        "cost_dollars": 22,
        "duration_min": 75,
        "description": "Neighborhood gastropub with house-cured charcuterie, creative sandwiches, and 40 taps. Unpretentious and excellent.",
        "distance_miles": 2.7,
        "cuisine": "American / Gastropub",
    },
    {
        "title": "Pho Saigon Noodle Bar",
        "block": "dinner",
        "tags": ["vietnamese", "ramen", "casual_dining", "solo_friendly", "community"],
        "location": "Pho Saigon",
        "address": "5700 Manor Rd",
        "cost_label": "$12–18/person",
        "cost_dollars": 15,
        "duration_min": 60,
        "description": "Massive bowls of pho, banh mi, and vermicelli. No-frills neighborhood institution that locals have loved for a decade.",
        "distance_miles": 4.1,
        "cuisine": "Vietnamese",
    },
    {
        "title": "Lenoir — Backyard Farm-to-Table",
        "block": "dinner",
        "tags": ["fine_dining", "american", "natural_wine", "solo_friendly", "couples"],
        "location": "Lenoir",
        "address": "1807 S 1st St",
        "cost_label": "$35–55/person",
        "cost_dollars": 45,
        "duration_min": 105,
        "description": "Intimate backyard restaurant sourcing almost entirely from Central Texas farms. BYOB-friendly, great natural wine list. Book ahead.",
        "distance_miles": 2.9,
        "cuisine": "American / Farm-to-table",
    },
    {
        "title": "Salt & Time Butcher Shop Dinner",
        "block": "dinner",
        "tags": ["american", "casual_dining", "east_austin", "community", "small_groups"],
        "location": "Salt & Time",
        "address": "1912 E 7th St",
        "cost_label": "$20–35/person",
        "cost_dollars": 27,
        "duration_min": 75,
        "description": "By day an artisan butcher; by night an excellent restaurant with house-cured charcuterie and Texas-sourced mains.",
        "distance_miles": 2.2,
        "cuisine": "American",
    },
    {
        "title": "Contigo — Texas Hill Country Cooking",
        "block": "dinner",
        "tags": ["american", "community", "nature_walks", "east_austin", "pet_friendly", "dogs"],
        "location": "Contigo",
        "address": "2027 Anchor Ln",
        "cost_label": "$20–38/person",
        "cost_dollars": 28,
        "duration_min": 90,
        "description": "Outdoor ranch-style seating, fire pits, and Texas Hill Country inspired cooking. Dogs welcome on the patio. Best vibes on a warm evening.",
        "distance_miles": 3.8,
        "cuisine": "Texas / American",
    },
    {
        "title": "Uchi — Modern Japanese",
        "block": "dinner",
        "tags": ["sushi", "fine_dining", "couples", "wine", "small_groups"],
        "location": "Uchi Austin",
        "address": "801 S Lamar Blvd",
        "cost_label": "$40–70/person",
        "cost_dollars": 55,
        "duration_min": 105,
        "description": "James Beard Award-winning sushi and Japanese cuisine. One of Austin's most acclaimed restaurants. Make a reservation — always busy.",
        "distance_miles": 3.1,
        "cuisine": "Japanese",
    },
    {
        "title": "Nixta Taqueria",
        "block": "dinner",
        "tags": ["mexican", "tacos", "casual_dining", "east_austin", "solo_friendly"],
        "location": "Nixta Taqueria",
        "address": "2512 E 12th St",
        "cost_label": "$12–22/person",
        "cost_dollars": 17,
        "duration_min": 60,
        "description": "Inventive masa-focused tacos with local and seasonal ingredients. Small counter-service spot in East Austin. Get the elote too.",
        "distance_miles": 3.0,
        "cuisine": "Mexican",
    },
    # ── NIGHTTIME ─────────────────────────────────────────────────────────────
    {
        "title": "Live Music at The Continental Club",
        "block": "nighttime",
        "tags": ["live_music", "south_congress", "cocktails", "live_music_venues", "folk", "country"],
        "location": "The Continental Club",
        "address": "1315 S Congress Ave",
        "cost_label": "$10–15 cover",
        "cost_dollars": 12,
        "duration_min": 120,
        "description": "Austin's most storied live music venue. Every night features roots, blues, and country from top local and touring acts. No reservations — just show up.",
        "distance_miles": 3.0,
    },
    {
        "title": "Comedy Night at Cap City Comedy Club",
        "block": "nighttime",
        "tags": ["comedy", "large_groups", "group_activities", "small_groups"],
        "location": "Cap City Comedy Club",
        "address": "8120 Research Blvd",
        "cost_label": "$15–25 + drink minimum",
        "cost_dollars": 25,
        "duration_min": 100,
        "description": "Austin's main comedy club with regional headliners on weekends. Arrive 30 min early for good seats. Two-drink minimum at the tables.",
        "distance_miles": 7.2,
    },
    {
        "title": "Rooftop Drinks at Geraldine's",
        "block": "nighttime",
        "tags": ["rooftop_bars", "cocktails", "small_groups", "live_music", "couples"],
        "location": "Geraldine's at Hotel Van Zandt",
        "address": "605 Davis St",
        "cost_label": "$12–18/drink",
        "cost_dollars": 30,
        "duration_min": 90,
        "description": "Rooftop bar with skyline views and live music most nights. One of Austin's best spots for drinks with a view without fighting the 6th Street crowd.",
        "distance_miles": 1.5,
    },
    {
        "title": "Late Night Jam — The Parish on 6th",
        "block": "nighttime",
        "tags": ["live_music", "6th_street", "cocktails", "indie_rock", "concerts", "late_night"],
        "location": "The Parish",
        "address": "214 E 6th St",
        "cost_label": "$10 cover",
        "cost_dollars": 10,
        "duration_min": 150,
        "description": "Two-floor venue on Dirty 6th. Upstairs: quiet cocktail bar. Downstairs: loud live music until 2am. Strong energy on Friday and Saturday.",
        "distance_miles": 1.2,
    },
    {
        "title": "Improv Show — Coldtowne Theater",
        "block": "nighttime",
        "tags": ["improv", "comedy", "theater", "small_groups", "community"],
        "location": "Coldtowne Theater",
        "address": "4110 Guadalupe St",
        "cost_label": "$10–12",
        "cost_dollars": 11,
        "duration_min": 90,
        "description": "Austin's beloved improv and comedy theater. Weekend shows range from beginner showcases to seasoned Harold teams. Very good for the price.",
        "distance_miles": 4.2,
    },
    {
        "title": "Jazz at Elephant Room",
        "block": "nighttime",
        "tags": ["jazz", "live_music", "dive_bars", "solo_friendly", "cocktails", "late_night"],
        "location": "The Elephant Room",
        "address": "315 Congress Ave",
        "cost_label": "$10 cover",
        "cost_dollars": 10,
        "duration_min": 120,
        "description": "Austin's premier jazz basement bar. Tight space, excellent musicians, cold drinks. The Thursday and Friday late sets are legendary.",
        "distance_miles": 1.8,
    },
    {
        "title": "Karaoke at Ego's",
        "block": "nighttime",
        "tags": ["karaoke", "dive_bars", "large_groups", "small_groups", "late_night"],
        "location": "Ego's Bar",
        "address": "510 S Congress Ave",
        "cost_label": "Free (drink minimum)",
        "cost_dollars": 10,
        "duration_min": 120,
        "description": "Austin's most beloved karaoke bar — a no-frills, big-hearted dive that's been running the same rotation for 30 years. Gets packed after 11pm.",
        "distance_miles": 3.3,
    },
    {
        "title": "Rainey Street Bar Hop",
        "block": "nighttime",
        "tags": ["bars", "rainey_street", "cocktails", "large_groups", "happy_hour", "community"],
        "location": "Rainey Street District",
        "address": "Rainey St & River St",
        "cost_label": "$5–15/drink",
        "cost_dollars": 20,
        "duration_min": 150,
        "description": "Austin's most social bar strip — bungalow-style bars and patios strung along two blocks. Good mix of chill and lively. Start at the south end.",
        "distance_miles": 1.0,
    },
    {
        "title": "Stay In — Low-Key Evening",
        "block": "nighttime",
        "tags": ["cozy", "movies", "reading", "solo_friendly", "board_games", "slow_mornings"],
        "location": "Home",
        "address": "",
        "cost_label": "Free",
        "cost_dollars": 0,
        "duration_min": 120,
        "description": "A book you've been meaning to finish, a movie, or a slow cook dinner. Rest is productive. Tonight might be a good night in.",
        "distance_miles": 0.0,
    },
]
